events {}

http {
    log_format main '$remote_addr "$request" $status client=$client_type';
    access_log /dev/stdout main;

    map $http_x_client_type $client_type {
        default unknown;
        "web" web;
        "mobile" mobile;
    }

    # Ключи зон
    map $client_type $mobile_key {
        mobile $binary_remote_addr;
    }

    map $client_type $web_key {
        web $binary_remote_addr;
    }

    map $client_type $unknown_key {
        unknown $binary_remote_addr;
    }

    limit_req_zone $mobile_key zone=mobile:10m rate=30r/s;
    limit_req_zone $web_key zone=web:10m rate=50r/s;
    limit_req_zone $unknown_key zone=unknown:10m rate=30r/s;

    upstream backend {
        server 127.0.0.1:8081;
    }

    server {
        listen 8080;

        # Веб и мобилки сейчас обращаются на этот ресурс
        location /api/ {
            limit_req zone=mobile burst=50;
            limit_req zone=web burst=70;
            limit_req zone=unknown burst=50;
            limit_req_status 429;

            # Передаем заголовок в наш бэк
            proxy_set_header Client-Type $client_type;
            proxy_pass http://backend;
        }
    }

    # Тестовый сервер для имитации бэкенда приложения
    server {
        listen 127.0.0.1:8081;

        location /api/ {
            default_type application/json;

            if ($http_client_type = "web") {
                return 200 '{"status": "success", "service": "web_backend", "data": "Web application response"}';
            }
            if ($http_client_type = "mobile") {
                return 200 '{"status": "success", "service": "mobile_backend", "data": "Mobile application response"}';
            }

            return 200 '{"status": "success", "service": "default_backend", "data": "Default response"}';
        }
    }
}
