http {
    map $http_x_client_type $client_type {
        default unknown;
        "web" web;
        "mobile" mobile;
    }

    map $client_type $mobile_key {
        mobile $binary_remote_addr;
    }

    map $client_type $web_key {
        web $binary_remote_addr;
    }

    map $client_type $unknown_key {
        unknown $binary_remote_addr;
    }
    
    limit_req_zone $mobile_key zone=mobile:10m rate=30r/s;
    limit_req_zone $web_key zone=web:10m rate=50r/s;
    limit_req_zone $unknown_key zone=unknown:10m rate=30r/s;

    server {
        listen 80;

        # Веб и мобилки сейчас обращаются на этот ресурс
        location /api/ {
            limit_req zone=mobile burst=50;
            limit_req zone=web burst=70;
            limit_req zone=unknown burst=50;
            limit_req_status 429;
            proxy_pass http://backend;
        }
    }
} 