apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels:
    app: test-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: test-app
